pipeline {
    agent {
        label "agent"; 
    }
    environment {
        project_id = sh(script: 'gcloud config get-value project', returnStdout: true).trim()
        artifact_registry = 'us-central1-docker.pkg.dev'
        artifact_name = 'pythonapp'
        repo = 'jenkins-repo'
        
    }
    stages {
        stage('Preparando el entorno') {
            steps {
                sh 'whoami'
                sh 'echo POR FAVOR !!!!!! fijaos en este dato'
                sh 'hostname'
                dir('app') {
                    sh 'python3 -m pip install -r requirements.txt'
                }
            }
        }
        
        stage('Calidad de código') {
            steps {
                sh 'whoami'
                sh 'hostname'
                dir('app') {
                    sh 'python3 -m pylint app.py'
                }
            }
        }

        stage('Tests') {         
            steps {
                sh 'whoami'
                sh 'hostname'
                dir('app') {
                    sh 'python3 -m pytest'
                }
            }
        }

        stage('Construcción del artefacto') {
            steps {
                sh 'whoami'
                sh 'hostname'
                dir('app') {
                    sh 'docker build . -t ${artifact_registry}/${project_id}/${repo}/${artifact_name}:${GIT_COMMIT}'
                }
            }
        }

        stage('Subir artefacto a repositorio docker') {
            steps {
                sh 'gcloud auth configure-docker ${artifact_registry} --quiet'
                sh 'docker push ${artifact_registry}/${project_id}/${repo}/${artifact_name}:${GIT_COMMIT}'
            }
        }

        stage('Verificar estado del contenedor') {
            steps {
                script {
                    def serviceName = 'pythonapp'  // Reemplaza con el nombre de tu servicio de Cloud Run
                    def containerRunning = sh(returnStatus: true, script: "gcloud run services describe ${serviceName} --format='value(status.url)'") == 0

                    if (containerRunning) {
                        echo "El contenedor está en ejecución. Se actualizará la imagen."
                        sh("gcloud run services update ${serviceName} --image=\"${artifact_registry}/${project_id}/${repo}/${artifact_name}:${GIT_COMMIT}\" --region\"us-central1\"")
                    } else {
                        echo "El contenedor no está en ejecución. Se realizará la implementación del servicio."
                        sh("gcloud run deploy ${serviceName} --image=\"${artifact_registry}/${project_id}/${repo}/${artifact_name}:${GIT_COMMIT}\" --region\"us-central1\"")
                    }
                }
            }
        }
    }

    // stage('Despliegue') {
    //     steps {
    //         sh 'whoami'
    //         sh ' echo si el dato anterior es root ... NOS HEMOS VUELTO LOCOS Y VAMOS A MORIR TODOS!!!!!!'
    //         sh 'hostname'
    //         sh 'docker run --name srgapp -d -p 5000:5000 srgjenkins:${GIT_COMMIT}'
    //     }
    // }
}
